"""initial_serenapsi_schema

Revision ID: 12ba6934ce4e
Revises: 
Create Date: 2026-08-08 15:12:06.995709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ba6934ce4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('model_class', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.Column('framework_version', sa.String(length=32), nullable=True),
    sa.Column('prompt_policy_version', sa.String(length=32), nullable=True),
    sa.Column('knowledge_base_version', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_requests'))
    )
    op.create_index(op.f('ix_ai_requests_organization_id'), 'ai_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_requests_patient_id'), 'ai_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_requests_task'), 'ai_requests', ['task'], unique=False)
    op.create_table('appointment_recurrences',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('rrule', sa.String(length=512), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_recurrences'))
    )
    op.create_index(op.f('ix_appointment_recurrences_organization_id'), 'appointment_recurrences', ['organization_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('charges',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('origin_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charges')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_charge_idempotency')
    )
    op.create_index(op.f('ix_charges_organization_id'), 'charges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_charges_patient_id'), 'charges', ['patient_id'], unique=False)
    op.create_index(op.f('ix_charges_status'), 'charges', ['status'], unique=False)
    op.create_table('clinical_hypotheses',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('formulation_id', sa.UUID(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('epistemology', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.String(length=32), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_hypotheses'))
    )
    op.create_index(op.f('ix_clinical_hypotheses_organization_id'), 'clinical_hypotheses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clinical_hypotheses_patient_id'), 'clinical_hypotheses', ['patient_id'], unique=False)
    op.create_table('consent_templates',
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_templates')),
    sa.UniqueConstraint('organization_id', 'consent_type', 'version', name='uq_consent_template_version')
    )
    op.create_index(op.f('ix_consent_templates_organization_id'), 'consent_templates', ['organization_id'], unique=False)
    op.create_table('document_templates',
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_templates'))
    )
    op.create_index(op.f('ix_document_templates_organization_id'), 'document_templates', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    op.create_table('expenses',
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_organization_id'), 'expenses', ['organization_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled_globally', sa.Boolean(), nullable=False),
    sa.Column('rollout_percent', sa.Integer(), nullable=False),
    sa.Column('organization_allowlist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('key', name=op.f('uq_feature_flags_key'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('default_session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('packages',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('used_sessions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages'))
    )
    op.create_index(op.f('ix_packages_organization_id'), 'packages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_packages_patient_id'), 'packages', ['patient_id'], unique=False)
    op.create_table('patients',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('internal_code', sa.String(length=32), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photo_object_key', sa.String(length=512), nullable=True),
    sa.Column('responsible_professional_id', sa.UUID(), nullable=True),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('session_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('therapeutic_approach', sa.String(length=64), nullable=True),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('finance_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guardian', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('organization_id', 'internal_code', name='uq_patient_org_code')
    )
    op.create_index(op.f('ix_patients_organization_id'), 'patients', ['organization_id'], unique=False)
    op.create_table('plans',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('tasks',
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_resource_type', sa.String(length=64), nullable=True),
    sa.Column('source_resource_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_assignee_user_id'), 'tasks', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_patient_id'), 'tasks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('professional_registration', sa.String(length=64), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('photo_object_key', sa.String(length=512), nullable=True),
    sa.Column('default_framework', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_outputs',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('structured_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('safety_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('critic_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ai_requests.id'], name=op.f('fk_ai_outputs_request_id_ai_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_outputs'))
    )
    op.create_index(op.f('ix_ai_outputs_organization_id'), 'ai_outputs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_outputs_patient_id'), 'ai_outputs', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmation_status', sa.String(length=32), nullable=True),
    sa.Column('recurrence_id', sa.UUID(), nullable=True),
    sa.Column('notes_admin', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_idempotency_key'), 'appointments', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('case_formulations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_case_formulations_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_formulations'))
    )
    op.create_index(op.f('ix_case_formulations_organization_id'), 'case_formulations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_case_formulations_patient_id'), 'case_formulations', ['patient_id'], unique=False)
    op.create_table('clinical_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_type', sa.String(length=64), nullable=False),
    sa.Column('evolution', sa.Text(), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('interventions', sa.Text(), nullable=True),
    sa.Column('relevant_observations', sa.Text(), nullable=True),
    sa.Column('tasks', sa.Text(), nullable=True),
    sa.Column('planning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_records_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_records'))
    )
    op.create_index(op.f('ix_clinical_records_organization_id'), 'clinical_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clinical_records_patient_id'), 'clinical_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_records_session_id'), 'clinical_records', ['session_id'], unique=False)
    op.create_table('consents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consents_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_organization_id'), 'consents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_table('memberships',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_key', sa.String(length=32), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_table('package_usages',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_usages_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_usages'))
    )
    op.create_index(op.f('ix_package_usages_organization_id'), 'package_usages', ['organization_id'], unique=False)
    op.create_table('payments',
    sa.Column('charge_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], name=op.f('fk_payments_charge_id_charges'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_payment_idempotency')
    )
    op.create_index(op.f('ix_payments_charge_id'), 'payments', ['charge_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_table('sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('events', sa.Text(), nullable=True),
    sa.Column('interventions', sa.Text(), nullable=True),
    sa.Column('responses', sa.Text(), nullable=True),
    sa.Column('hypotheses', sa.Text(), nullable=True),
    sa.Column('tasks', sa.Text(), nullable=True),
    sa.Column('agreements', sa.Text(), nullable=True),
    sa.Column('planning', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autosave_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incomplete_reason', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_sessions_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_appointment_id'), 'sessions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_sessions_organization_id'), 'sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority_problems', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('initial_formulation_summary', sa.Text(), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_treatment_plans_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_plans'))
    )
    op.create_index(op.f('ix_treatment_plans_organization_id'), 'treatment_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('output_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['output_id'], ['ai_outputs.id'], name=op.f('fk_ai_feedback_output_id_ai_outputs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback'))
    )
    op.create_index(op.f('ix_ai_feedback_organization_id'), 'ai_feedback', ['organization_id'], unique=False)
    op.create_table('treatment_goals',
    sa.Column('treatment_plan_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('specific_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], name=op.f('fk_treatment_goals_treatment_plan_id_treatment_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_goals'))
    )
    op.create_index(op.f('ix_treatment_goals_organization_id'), 'treatment_goals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_treatment_goals_patient_id'), 'treatment_goals', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_goals_patient_id'), table_name='treatment_goals')
    op.drop_index(op.f('ix_treatment_goals_organization_id'), table_name='treatment_goals')
    op.drop_table('treatment_goals')
    op.drop_index(op.f('ix_ai_feedback_organization_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_organization_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organization_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_appointment_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_charge_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_package_usages_organization_id'), table_name='package_usages')
    op.drop_table('package_usages')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_organization_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_clinical_records_session_id'), table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_patient_id'), table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_organization_id'), table_name='clinical_records')
    op.drop_table('clinical_records')
    op.drop_index(op.f('ix_case_formulations_patient_id'), table_name='case_formulations')
    op.drop_index(op.f('ix_case_formulations_organization_id'), table_name='case_formulations')
    op.drop_table('case_formulations')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_idempotency_key'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_outputs_patient_id'), table_name='ai_outputs')
    op.drop_index(op.f('ix_ai_outputs_organization_id'), table_name='ai_outputs')
    op.drop_table('ai_outputs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_patient_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('plans')
    op.drop_index(op.f('ix_patients_organization_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_packages_patient_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_organization_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_expenses_organization_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_templates_organization_id'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_consent_templates_organization_id'), table_name='consent_templates')
    op.drop_table('consent_templates')
    op.drop_index(op.f('ix_clinical_hypotheses_patient_id'), table_name='clinical_hypotheses')
    op.drop_index(op.f('ix_clinical_hypotheses_organization_id'), table_name='clinical_hypotheses')
    op.drop_table('clinical_hypotheses')
    op.drop_index(op.f('ix_charges_status'), table_name='charges')
    op.drop_index(op.f('ix_charges_patient_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_organization_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_appointment_recurrences_organization_id'), table_name='appointment_recurrences')
    op.drop_table('appointment_recurrences')
    op.drop_index(op.f('ix_ai_requests_task'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_patient_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_organization_id'), table_name='ai_requests')
    op.drop_table('ai_requests')
    # ### end Alembic commands ###
