"""case_memory_entries

Revision ID: ffa3de654618
Revises: 12ba6934ce4e
Create Date: 2026-08-08 15:58:30.009143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffa3de654618'
down_revision: Union[str, Sequence[str], None] = '12ba6934ce4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_memory_entries',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('epistemology', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_memory_entries'))
    )
    op.create_index(op.f('ix_case_memory_entries_kind'), 'case_memory_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_case_memory_entries_organization_id'), 'case_memory_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_case_memory_entries_patient_id'), 'case_memory_entries', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_memory_entries_patient_id'), table_name='case_memory_entries')
    op.drop_index(op.f('ix_case_memory_entries_organization_id'), table_name='case_memory_entries')
    op.drop_index(op.f('ix_case_memory_entries_kind'), table_name='case_memory_entries')
    op.drop_table('case_memory_entries')
    # ### end Alembic commands ###
